### ISSUE TITLE
显示不出来

### ISSUE THREAD

**Issue by gonghai84** [jtydhr88/sd-webui-3d-editor#12]
![image](https://github.com/jtydhr88/sd-webui-3d-editor/assets/80751871/0e578cc1-fbfa-46df-baef-53d161c93f0e)

**Comment by jtydhr88** [comment]
你好，请按一下F12，然后选择console标签，能帮我看下里面有没有红色的error信息吗，多谢。

**Comment by gonghai84** [comment]
![image](https://github.com/jtydhr88/sd-webui-3d-editor/assets/80751871/aaec34d7-b47b-453a-8afe-e1c4be74168e)

**Comment by jtydhr88** [comment]
从log信息上看，你在用阿里云的环境，然后不支持“域名+file=xxx"这种方式读取本地文件，我还没在ubuntu/linux或是云上跑过sd-webui，我自己都是本地localhost环境...

**Comment by gonghai84** [comment]
是的，我在本地上也可以使用了
