### ISSUE TITLE
UI Theme Becoming Dull

### ISSUE THREAD

**Issue by JPW0080** [jtydhr88/sd-webui-3d-editor#5]
The extension appears to be changing the overall UI Theme to somewhat duller.
AUTOMATIC1111 stable-diffusion-webui v1.4.0

Win 11
Mozilla Firefox
Microsoft Edge
Google Chrome

Before: Disregard the other Extensions, The UI Theme issue remained prevalent.
![Default](https://github.com/jtydhr88/sd-webui-3d-editor/assets/104588046/b9e9b53e-1c92-4a44-9321-8347500d4782)

After:
![UI-Theme](https://github.com/jtydhr88/sd-webui-3d-editor/assets/104588046/1ed0dc74-e620-43c5-9a59-cff98804f997)

**Comment by jtydhr88** [comment]
@JPW0080 can you highlight the problem where? Thanks

**Comment by DunkedOn** [comment]
> @JPW0080 can you highlight the problem where? Thanks

Same issue. The problem here is this warm black theme instead of the regular one, so it is practically everywhere.

**Comment by jtydhr88** [comment]
@DunkedOn thanks for reporting, will fix sonn

**Comment by jtydhr88** [comment]
thanks for the feedback, I think I fixed the issue.
please feel free to open new one if you guys have more issues

**Comment by JPW0080** [comment]
Gave it a go but unfortunately:

![Color-Change2](https://github.com/jtydhr88/sd-webui-3d-editor/assets/104588046/33a457c0-ef55-4398-9c42-7ffba8d158ce)

**Comment by jtydhr88** [comment]
@JPW0080 please clean up your browser cache first

**Comment by JPW0080** [comment]
That was it, the issue has been resolved. Thanks.
